const fs=require('node:fs');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const code=fs.readFileSync('app.js','utf8');
assert(code.includes("data/editorial-reports.json"),'Editorial JSON source missing');
assert(code.includes("function reportStory(m)"),'Report rendering missing');
assert(code.includes("function bindPhotoFallbacks(root){$$("),'Photo query must return a list');
assert(code.includes("$$('.match-tab',$('#matchDialog')).forEach"),'Tab query must return a list');
assert(code.includes("function editorialStory(m)"),'Editorial report lookup missing');
const card=code.slice(code.indexOf('function card(m){'),code.indexOf('function renderMatches()'));
const hero=code.slice(code.indexOf('function renderHero(){'),code.indexOf('function renderFilters()'));
const dialog=code.slice(code.indexOf('function openMatch(id){'),code.indexOf('async function json('));
assert(card.indexOf('match-card-headline')<card.indexOf('match-meta'),'Card headline must appear above match data');
assert(hero.indexOf('featured-editorial')<hero.indexOf('featured-teams'),'Featured title must appear above scoreboard');
assert(dialog.indexOf('dialog-editorial-headline')<dialog.indexOf('dialog-scoreboard'),'Dialog headline must appear above scoreboard');
assert(code.includes('data-panel="report">${reportStory(m)}${photoGallery(m)}'),'Story must appear before photos in report');
new vm.Script(code,{filename:'app.js'});
console.log('Frontend syntax and wiring smoke checks passed.');
